export const CREATIVE_SKILLS = {
  'Design Skills': [
    'Ability to create layouts using Adobe Photoshop',
    'Ability to create vector-based designs using Adobe Illustrator or CorelDRAW',
    'Preparing print-ready files (correct size, bleed, color mode, resolution)',
    'Translating client instructions into accurate visual layouts',
    'Applying branding guidelines and visual consistency',
    'Designing creatives for social media and digital platforms',
    'Accuracy and attention to detail during revisions and final checking',
    'Understanding production limitations when designing',
    'Speed and efficiency in completing design tasks without sacrificing quality',
    'Ability to troubleshoot and correct layout or file issues independently',
    'Ability to create social media creatives',
    'Ability to run ads on different social media platforms',
    'Ability to compose content scripts',
    'Ability to create websites and landing pages',
    'Ability to manipulate and retouch images',
  ],
  'Operations Skills': [
    'Understanding job orders and instructions accurately',
    'Following SOPs and internal processes',
    'Time management and meeting deadlines',
    'Attention to detail in assigned tasks',
    'Problem-solving during work challenges',
    'Ability to work under pressure',
    'Team coordination and cooperation',
    'Proper use and care of company tools and equipment',
    'Tarpaulin Printing Machine Operation',
    'Cutter Plotter Machine Operation',
    'Laser Cutting Operation',
    'Heat Press Machine Operation',
    'Manual Laminating Machine Operation',
    'Ability to laminate stickers without using a laminator',
    'Sticker application on sintra and acrylics',
  ],
}

export const PRODUCTION_SKILLS = {
  'Fabrication Skills': [
    'Tarpaulin Printing Machine Operation',
    'Cutter Plotter Machine Operation',
    'Laser Cutting Operation',
    'Heat Press Machine Operation',
    'Manual Laminating Machine Operation',
    'Ability to laminate stickers without using a laminator',
    'Cutting/Trimming Accuracy using cutters',
    'Cutting/Trimming Accuracy using grinders',
    'Power Tools and Equipment Handling',
    'Sticker Application on Walls and Glass',
    'Sticker Application on Vehicles',
    'Sticker Application on Sintra',
    'Tending flex/tarpaulins on frames for panaflex and digiflex',
    'Welding frames',
    'Applying stickers on signage and flex',
    'Installing LED tube lights on panaflex and digiflex signages',
    'Installing LED modules on signages and wiring to power supplies',
    'Tapping signage circuits to electricity source for lighting',
    'Buildup signages using Sintra boards and Versa boards',
    'Buildup signages using Acrylic',
    'Buildup signages using Stainless',
    'Buildup signages using ACP',
    'Manually cut sticker letters',
    'Manually cut stainless elements and logos',
    'Installation of indoor signages',
    'Installation of outdoor signages',
    'Ability to paint evenly using spray paints',
    'Ability to paint using compressor',
    'Ability to glue acrylic without stains',
    'Ability to seam tarpaulins',
  ],
}

export type SkillsMap = typeof CREATIVE_SKILLS | typeof PRODUCTION_SKILLS
